### PR TITLE
Linking to the correct issue page in README

### PR DESCRIPTION
**Pull request by vringar**
## Purpose
Previously pointed to https://github.com/siddhi-io/siddhi-execution-string/issues which is not this repository

## Release note
Fixed typo in README.md

### CODE REVIEW

**Comment by vringar** [comment]
Sorry if I deleted too much of the template but all of the other ones weren't really applicable

**Review by mohanvive — APPROVED** [review]

**Comment by vringar** [comment]
Wait a sec I just realized it's from in docs/index.md as well

**Comment by vringar** [comment]
Done and ready for merge :)

**Comment by mohanvive** [comment]
Thanks @vringar for the PR. Appreciate it. No worries, your fix it perfect, 
BTW, index.md also get updated in a release based on the content of readme..

**Comment by vringar** [comment]
Oki, good to know. :slightly_smiling_face:

**Pull request merged**
